// <auto-generated />
namespace LeaveSystem.DomainModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedreqtextfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedreqtextfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231518029_addedreqtextfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
